export default {
    CREATE_BOOK : "CREATE_BOOK",
    REMOVE_BOOK : "REMOVE_BOOK",
    SELECTED_BOOKS: "SELECTED_BOOKS",
    TOGGLE_WHEN_BOOK_SEARCHED : "TOGGLE_WHEN_BOOK_SEARCHED",
    CREATE_USER : "CREATE_USER",
    AUTH_USER : "AUTH_USER"
}